salonrama_main_index:
    pattern:  /
    defaults: { _controller: SalonramaMainBundle:Index:index }

salonrama_main_contact:
    pattern:  /contact
    defaults: { _controller: SalonramaMainBundle:Contact:contact }

salonrama_main_login:
    pattern:  /login
    defaults: { _controller: SalonramaMainBundle:Login:login }

salonrama_main_login_check:
    pattern:  /login_check

salonrama_main_forgot_password:
    pattern:  /forgot_password
    defaults: { _controller: SalonramaMainBundle:ForgotPassword:forgotPassword }

salonrama_main_logout:
    pattern:  /logout

salonrama_main_presse:
    pattern:  /presse
    defaults: { _controller: SalonramaMainBundle:Presse:presse }

salonrama_main_about:
    pattern:  /about
    defaults: { _controller: SalonramaMainBundle:About:about }

salonrama_main_legal:
    pattern:  /legal
    defaults: { _controller: SalonramaMainBundle:Legal:legal }

salonrama_main_help:
    pattern:  /help
    defaults: { _controller: SalonramaMainBundle:Help:help }

salonrama_main_help_articles:
    pattern:  /help/article/{id}
    defaults: { _controller: SalonramaMainBundle:Help:article }

salonrama_main_account:
    pattern:  /account/
    defaults: { _controller: SalonramaMainBundle:Index:index }

salonrama_main_account_settings:
    pattern:  /account/settings/
    defaults: { _controller: SalonramaMainBundle:SettingsGeneral:general }

salonrama_main_account_settings_general:
    pattern:  /account/settings/general
    defaults: { _controller: SalonramaMainBundle:SettingsGeneral:general }

salonrama_main_account_settings_email:
    pattern:  /account/settings/email
    defaults: { _controller: SalonramaMainBundle:SettingsEmail:email }

salonrama_main_account_settings_password:
    pattern:  /account/settings/password
    defaults: { _controller: SalonramaMainBundle:SettingsPassword:password }

salonrama_main_account_settings_delete:
    pattern:  /account/settings/delete
    defaults: { _controller: SalonramaMainBundle:SettingsDelete:delete }

salonrama_main_signin:
    pattern:  /signin
    defaults: { _controller: SalonramaMainBundle:Signin:signin }