salonrama_main_index:
    pattern:  /
    defaults: { _controller: SalonramaMainBundle:Index:index }

salonrama_main_contact:
    pattern:  /contact
    defaults: { _controller: SalonramaMainBundle:Contact:contact }

salonrama_main_presentation:
    pattern:  /presentation
    defaults: { _controller: SalonramaMainBundle:Presentation:presentation }

salonrama_main_login:
    pattern:  /login
    defaults: { _controller: SalonramaMainBundle:Login:login }

salonrama_main_login_check:
    pattern:  /login_check

salonrama_main_forgot_password:
    pattern:  /forgot_password
    defaults: { _controller: SalonramaMainBundle:ForgotPassword:forgotPassword }

salonrama_main_reset_password:
    pattern:  /reset_password/{id}/{token}
    defaults: { _controller: SalonramaMainBundle:ResetPassword:resetPassword }

salonrama_main_logout:
    pattern:  /logout

salonrama_main_presse:
    pattern:  /presse
    defaults: { _controller: SalonramaMainBundle:Presse:presse }

salonrama_main_about:
    pattern:  /a_propos
    defaults: { _controller: SalonramaMainBundle:About:about }

salonrama_main_legal:
    pattern:  /legal
    defaults: { _controller: SalonramaMainBundle:Legal:legal }

salonrama_main_policy:
    pattern:  /conditions
    defaults: { _controller: SalonramaMainBundle:Policy:policy }

salonrama_main_buildsite_step1:
    pattern:  /buildsite/step1
    defaults: { _controller: SalonramaMainBundle:Buildsite/Step1:step1 }

salonrama_main_buildsite_step2:
    pattern:  /buildsite/step2
    defaults: { _controller: SalonramaMainBundle:Buildsite/Step2:step2 }

salonrama_main_buildsite_step3:
    pattern:  /buildsite/step3
    defaults: { _controller: SalonramaMainBundle:Buildsite/Step3:step3 }

salonrama_main_buildsite_step4:
    pattern:  /buildsite/step4
    defaults: { _controller: SalonramaMainBundle:Buildsite/Step4:step4 }

salonrama_main_buildsite_step5:
    pattern:  /buildsite/step5
    defaults: { _controller: SalonramaMainBundle:Buildsite/Step5:step5 }

salonrama_main_buildsite_theme_get_structure:
    pattern: /buildsite/theme/get_structure
    defaults: { _controller: SalonramaMainBundle:Buildsite/Theme:getStructure }

salonrama_main_buildsite_theme_get_inte:
    pattern: /buildsite/theme/get_inte
    defaults: { _controller: SalonramaMainBundle:Buildsite/Theme:getInte }

salonrama_main_buildsite_preview:
    pattern: /buildsite/preview
    defaults: { _controller: SalonramaMainBundle:Buildsite/Preview:preview }

salonrama_main_buildsite_wys:
    pattern: /buildsite/wys
    defaults: { _controller: SalonramaMainBundle:Buildsite/Wys:wys }

salonrama_main_buildsite_save:
    pattern: /buildsite/save
    defaults: { _controller: SalonramaMainBundle:Buildsite/Save:save }

salonrama_main_buildsite_image:
    pattern: /buildsite/image
    defaults: { _controller: SalonramaMainBundle:Buildsite/Image:image }

salonrama_main_help:
    pattern:  /aide
    defaults: { _controller: SalonramaMainBundle:Help:help }

salonrama_main_help_articles:
    pattern:  /aide/article/{id}
    defaults: { _controller: SalonramaMainBundle:Help:article }

salonrama_main_confirm_email:
    pattern:  /confirm_email/{id}/{token}
    defaults: { _controller: SalonramaMainBundle:ConfirmEmail:confirmEmail }

salonrama_main_confirm_email_send:
    pattern:  /confirm_email/{email}
    defaults: { _controller: SalonramaMainBundle:ConfirmEmail:confirmEmailSend }

salonrama_main_account:
    pattern:  /mon_compte/
    defaults: { _controller: SalonramaMainBundle:Account/Index:index }

salonrama_main_account_confirm_email:
    pattern:  /mon_compte/confirm_email/{id}/{token}
    defaults: { _controller: SalonramaMainBundle:Account/ConfirmEmail:confirmEmail }

salonrama_main_account_site:
    pattern:  /mon_compte/site
    defaults: { _controller: SalonramaMainBundle:Account/Site:site }

salonrama_main_account_salon:
    pattern:  /mon_compte/salon
    defaults: { _controller: SalonramaMainBundle:Account/Salon:salon }

salonrama_main_account_settings:
    pattern:  /mon_compte/settings/
    defaults: { _controller: SalonramaMainBundle:Account/SettingsGeneral:general }

salonrama_main_account_settings_general:
    pattern:  /mon_compte/settings/general
    defaults: { _controller: SalonramaMainBundle:Account/SettingsGeneral:general }

salonrama_main_account_settings_email:
    pattern:  /mon_compte/settings/email
    defaults: { _controller: SalonramaMainBundle:Account/SettingsEmail:email }

salonrama_main_account_settings_password:
    pattern:  /mon_compte/settings/password
    defaults: { _controller: SalonramaMainBundle:Account/SettingsPassword:password }

salonrama_main_account_settings_delete:
    pattern:  /mon_compte/settings/delete
    defaults: { _controller: SalonramaMainBundle:Account/SettingsDelete:delete }

salonrama_main_signin:
    pattern:  /signin
    defaults: { _controller: SalonramaMainBundle:Signin:signin }