parameters:
#    salonrama_main.example.class: Salonrama\MainBundle\Example

services:
    salonrama_main_mailer:
        class: Salonrama\MainBundle\Mailer
        arguments: ['@mailer', '@templating']

    login_listener:
        class: Salonrama\MainBundle\Listener\LoginListener
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    salonrama_main_subdomain:
        class: Salonrama\MainBundle\Subdomain
        arguments: ['@doctrine']

    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    session.storage.native:
        class:     Salonrama\MainBundle\Session\Storage
        arguments: [%session.storage.options%, @service_container]