parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: salonrama
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_host: null
    mailer_user: olivier.tassinari@gmail.com
    mailer_password: anihilus1302
    locale: fr
    secret: 7cc10e4a66486ee465b66d70b4c5a22f77911488
    database_path: null
