security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        account:
            entity: { class: SalonramaMainBundle:Account, property: email }

    firewalls:
        account:
            pattern:    ^/account/
            form_login:
                login_path: /login/
                check_path: /login/
            logout:
                path:   /logout/
                target: /
            provider:  account

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~

    access_control:
        - { path: ^/account/, roles: ROLE_ADMIN }