security:
    encoders:
        Salonrama\MainBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
        user_provider:
            entity: { class: SalonramaMainBundle:User }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: salonrama_main_login
                check_path: salonrama_main_login_check
                provider:   user_provider
                username_parameter: email
                password_parameter: password
            remember_me:
                key:      "%secret%"
                lifetime: 1209600 # 14 jours en secondes
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/mon_compte/, roles: ROLE_USER }