security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
             memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: salonrama_main_login
                check_path: salonrama_main_login_check

    access_control:
        - { path: ^/account/, roles: ROLE_ADMIN }